Ensure gdb.events.stop.disconnect() is only called once.
Fixes a scenario where a user would be at the prompt in GDB without
having loaded a program and a Python exception is raised due to the
on_attach_first_stop() callback already having been unregistered.

    SystemError: <method 'disconnect' of 'gdb.EventRegistry' objects>
    returned a result with an exception set

    ValueError: sequence.index(x): x not in sequence