Skip attempting to set thread names when no program or core dump.
Fixes a scenario where a user would be at the prompt in GDB with an
executable file loaded and a Python exception is raised due to the
_set_thread_names() function attempting to save the current thread
and frame.

    gdb.error: No frame is currently selected.